name: money_manager
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  flutter_bloc: 0.18.3
  equatable: 0.2.6
  base_bloc:
    git:
      url: https://github.com/trgcuong/base_bloc.git
      ref: 0.0.3

  cupertino_icons: 0.1.2
  firebase_crashlytics: 0.0.4+8
  sticky_headers: 0.1.8
  tuple: 1.0.2
  prefs: 3.0.0
  flutter_easyrefresh: 1.2.7
  hidden_drawer_menu: 1.1.1
  firebase_database: 3.0.3
  bottom_navy_bar: 5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  fonts:
      - family: Roboto
        fonts:
          - asset: fonts/Roboto-Regular.ttf

      - family: Roboto-Bold
        fonts:
          - asset: fonts/Roboto-Bold.ttf
            weight: 700

      - family: Roboto-Italic
        fonts:
          - asset: fonts/Roboto-Italic.ttf

      - family: Roboto-Thin
        fonts:
          - asset: fonts/Roboto-Thin.ttf

      - family: Roboto-ThinItalic
        fonts:
          - asset: fonts/Roboto-ThinItalic.ttf
