/// Flutter icons MoneyManager
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MoneyManager
///      fonts:
///       - asset: fonts/MoneyManager.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MoneyManager {
  MoneyManager._();

  static const _kFontFam = 'MoneyManager';

  static const IconData wallet = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData divide = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData minus = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData eq = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData cancel_alt_filled = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData cancel = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData plus = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData money = const IconData(0xf0d6, fontFamily: _kFontFam);
}
